apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fastapi
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  DATABASE_URL: postgresql://postgres:password@postgres-svc:5432/cruddb