name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # pulls your code into the GitHub Actions runner.
      - name: Checkout code
        uses: actions/checkout@v3

      # authenticates using GITHUB_TOKEN which GitHub provides automatically, no setup needed.
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      #  builds your Dockerfile and pushes to ghcr.io/yourusername/fastapi-crud:latest.
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/m-syaifudin/k3d-fastapi-nginx:latest

      #  SSHes into your VPS and tells Kubernetes to use the new image.
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            kubectl set image deployment/fastapi-app fastapi-app=ghcr.io/${{ github.repository }}:latest -n fastapi
            kubectl rollout status deployment/fastapi-app -n fastapi